services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: getjob-backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://47.96.178.102:5432/postgres?user=postgres&password=wsad123456
      DB_USERNAME: postgres
      DB_PASSWORD: wsad123456
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - getjob-network

networks:
  getjob-network:
    driver: bridge